### ISSUE TITLE
No such file or directory: 'virtualenv' when doing pipsi install pew

### ISSUE THREAD

**Issue by cjw296** [mitsuhiko/pipsi#125]
Here's a shell session:

```
tweedledee:~ chris$ curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python3.6
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4130  100  4130    0     0  21211      0 --:--:-- --:--:-- --:--:-- 21179
Installing pipsi
Collecting pipsi
  Using cached pipsi-0.9.tar.gz
Collecting Click (from pipsi)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting virtualenv (from pipsi)
  Using cached virtualenv-15.1.0-py2.py3-none-any.whl
Installing collected packages: Click, virtualenv, pipsi
  Running setup.py install for pipsi ... done
Successfully installed Click-6.7 pipsi-0.9 virtualenv-15.1.0
Installed pipsi binary in /Users/chris/.local/bin
pipsi is now installed.
tweedledee:~ chris$ pipsi install pew
Traceback (most recent call last):
  File "/Users/chris/.local/bin/pipsi", line 11, in <module>
    load_entry_point('pipsi==0.9', 'console_scripts', 'pipsi')()
  File "/Users/chris/.local/venvs/pipsi/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/chris/.local/venvs/pipsi/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/chris/.local/venvs/pipsi/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chris/.local/venvs/pipsi/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/chris/.local/venvs/pipsi/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/chris/.local/venvs/pipsi/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/chris/.local/venvs/pipsi/lib/python3.6/site-packages/pipsi.py", line 366, in install
    if repo.install(package, python, editable):
  File "/Users/chris/.local/venvs/pipsi/lib/python3.6/site-packages/pipsi.py", line 236, in install
    if Popen(args).wait() != 0:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'virtualenv'
```

What am I or have I done wrong?

**Comment by cjw296** [comment]
Hmm, chicken and egg if I try 2.7:

```
tweedledee:~ chris$ curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4130  100  4130    0     0  25417      0 --:--:-- --:--:-- --:--:-- 25493
Installing pipsi
You need to have virtualenv installed to bootstrap pipsi.
```

**Comment by buzzjmd** [comment]
I had a similar problem and there are many similar related issues reported. I believe they relate to release 0.9, which is the most recent release available, and is the version installed by the recommended installation procedure

	curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python

There hasn't been a new release for a long time, so I installed pipsi from the master and this fixed the issue (probably thanks to commit [be4abc4](https://github.com/mitsuhiko/pipsi/commit/be4abc4fe968d5c775ff16a1abaff4c18786e709)). Try installing from master :-

	# Download the pipsi installer script from github
	$ curl -O https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py

	# Read about the --src option in the help menu
	$ python get-pipsi.py --help
	
	# Run the installer script to get the master branch from github
	$ python get-pipsi.py --src=git+https://github.com/mitsuhiko/pipsi.git#egg=pipsi

**Comment by cjw296** [comment]
Could anyone persuade @mitsuhiko to do a new release?

**Comment by jacobian** [comment]
I worked around this by creating `~/.local/vens/pipsi/package_info.json` containing `{"name": "pipsi", "version": "0.10.dev", "script": ["pipsi"]}`.

**Comment by jacobian** [comment]
Oops, I meant to leave that comment on #124.

**Comment by halicki** [comment]
In my case (ubuntu 17.10) solution provided by @cjw296 had to have a modification. Instead of providing `--src=git+https://github.com/mitsuhiko/pipsi.git#egg=pipsi` I used `--src=git+https://github.com/mitsuhiko/pipsi.git` so, removed the egg info, and that helped!

**Comment by cjw296** [comment]
Doesn't look like this package is maintained anymore, I don't use it and @amartin1911 has provided a workaround, so closing.

**Comment by jakul** [comment]
I was also able to workaround this, by manually installing `virtualenv` in the environment of the base python pipsi uses:

```
$ curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python3
$ pip3 install virtualenv
```

**Comment by bbrendon** [comment]
Failed out of the gate.
```
% curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6577  100  6577    0     0  14833      0 --:--:-- --:--:-- --:--:-- 14846
Installing pipsi
You need to have virtualenv installed to bootstrap pipsi.
% dpkg -l|grep virtual
ii  python3-virtualenv                 15.1.0+ds-1                       all          Python virtual environment creator
ii  virtualenv                         15.1.0+ds-1                       all          Python virtual environment creator
% uname -a
Linux homeauto 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
```
