### ISSUE TITLE
Installation fails : ImportError: cannot import name _remove_dead_weakref

### ISSUE THREAD

**Issue by Craigson** [mitsuhiko/pipsi#128]
Running on OSX 10.13.2

```
youAreHere  => curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4130  100  4130    0     0   9661      0 --:--:-- --:--:-- --:--:--  9672
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 86, in <module>
    import copy as _copy
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
```

**Comment by RonnyPfannschmidt** [comment]
this looks like a broken python, nothing pipsi can do about that
