### ISSUE TITLE
"TypeError: coercing to Unicode:..." while installing pipsi

### ISSUE THREAD

**Issue by Jaxmetalmax** [mitsuhiko/pipsi#163]
Error while installing pipsi via:
``` curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python ```

It seems that is trying to change PATH, fixed with adding ~/.local/bin to PATH on .bashrc manually

Environment
OS: Debian 9
Python 2.7.13
TraceBack: 

```
Installed pipsi binary in /home/developer/.local/bin
Traceback (most recent call last):
  File "<stdin>", line 237, in <module>
  File "<stdin>", line 232, in main
  File "<stdin>", line 188, in ensure_pipsi_on_path
  File "/usr/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by Jaxmetalmax** [comment]
@arnavb after install just make sure that you have or add ~/.local/bin to PATH, while this is fixed.
