### ISSUE TITLE
pipsi list fails before first install

### ISSUE THREAD

**Issue by kwill** [mitsuhiko/pipsi#169]
**Steps to reproduce:**

* Install pipsi
* Do not install any packages yet
* `pipsi list`

**What should happen:**

* Returns empty list

**What happens instead:**

```
Packages and scripts installed through pipsi:
Traceback (most recent call last):
  File "/usr/bin/pipsi", line 11, in <module>
    load_entry_point('pipsi==0.9', 'console_scripts', 'pipsi')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipsi.py", line 416, in list_cmd
    for venv, scripts in repo.list_everything():
  File "/usr/lib/python3/dist-packages/pipsi.py", line 307, in list_everything
    for venv in os.listdir(self.home):
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.local/venvs'
```

**Notes:**

* If I install a package and then uninstall it, an empty list is returned, as expected.

* Ideally it would return something more descriptive in both cases:

```
Packages and scripts installed through pipsi:
  None
```

* Version details:

```
$ pipsi --version                                                                                                                                                   
pipsi, version 0.9, python /usr/bin/python3
```

**Comment by simlun** [comment]
This seems to be fixed on `master`.

**Comment by cs01** [comment]
I recently started a project called pipx that combines pipsi's functionality with npx's. Running `pipx list` after initial install yields
```
>> pipx list
venvs are in /Users/user/.local/pipx/venvs, symlinks to binaries are in /Users/user/.local/bin
package pipx 0.0.0.5, symlinks to binaries available: pipx
```
Would love to hear what you think! https://github.com/cs01/pipx

**Comment by jambonrose** [comment]
I've just installed pipsi on a new machine, and I am seeing a similar error (but slightly different).

```console
$ curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python3.7 - --src 'git+https://github.com/mitsuhiko/pipsi.git#egg=pipsi'
$ # add export PATH=/Users/andrew/.local/bin:$PATH to .profile
$ pipsi --version
pipsi, version 0.10.dev0, python /Users/andrew/.local/venvs/pipsi/bin/python3.7
$ pipsi list
Traceback (most recent call last):
  File "/Users/andrew/.local/bin/pipsi", line 11, in <module>
    load_entry_point('pipsi==0.10.dev0', 'console_scripts', 'pipsi')()
  File "/Users/andrew/.local/venvs/pipsi/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/andrew/.local/venvs/pipsi/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/andrew/.local/venvs/pipsi/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/andrew/.local/venvs/pipsi/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/andrew/.local/venvs/pipsi/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/andrew/.local/venvs/pipsi/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/andrew/.local/venvs/pipsi/lib/python3.7/site-packages/pipsi/__init__.py", line 538, in list_cmd
    for venv, scripts in repo.list_everything()
  File "/Users/andrew/.local/venvs/pipsi/lib/python3.7/site-packages/pipsi/__init__.py", line 434, in list_everything
    info = self.get_package_info(venv_path)
  File "/Users/andrew/.local/venvs/pipsi/lib/python3.7/site-packages/pipsi/__init__.py", line 304, in get_package_info
    with open(package_info_file_path, 'r') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/andrew/.local/venvs/pipsi/package_info.json'
```
