### ISSUE TITLE
install tox under python3 failed

### ISSUE THREAD

**Issue by heww** [mitsuhiko/pipsi#5]
On my system (Archlinux), virtualenv is for py3, and virtualenv2 for py2 . 'curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python' will install get-pipsi with py3 and virtualenv. After that, I will install tox with pipsi, but failed.

```bash
Successfully installed tox virtualenv py
Cleaning up...
Traceback (most recent call last):
  File "/home/phoenix/.local/bin/pipsi", line 9, in <module>
    load_entry_point('pipsi==0.6', 'console_scripts', 'pipsi')()
  File "/home/phoenix/.local/venvs/pipsi/lib/python3.4/site-packages/click/core.py", line 488, in __call__
    return self.main(*args, **kwargs)
  File "/home/phoenix/.local/venvs/pipsi/lib/python3.4/site-packages/click/core.py", line 474, in main
    self.invoke(ctx)
  File "/home/phoenix/.local/venvs/pipsi/lib/python3.4/site-packages/click/core.py", line 758, in invoke
    return self.invoke_subcommand(ctx, cmd, cmd_name, ctx.args[1:])
  File "/home/phoenix/.local/venvs/pipsi/lib/python3.4/site-packages/click/core.py", line 767, in invoke_subcommand
    return cmd.invoke(cmd_ctx)
  File "/home/phoenix/.local/venvs/pipsi/lib/python3.4/site-packages/click/core.py", line 659, in invoke
    ctx.invoke(self.callback, **ctx.params)
  File "/home/phoenix/.local/venvs/pipsi/lib/python3.4/site-packages/click/core.py", line 325, in invoke
    return callback(*args, **kwargs)
  File "/home/phoenix/.local/venvs/pipsi/lib/python3.4/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/phoenix/.local/venvs/pipsi/lib/python3.4/site-packages/click/core.py", line 325, in invoke
    return callback(*args, **kwargs)
  File "/home/phoenix/.local/venvs/pipsi/lib/python3.4/site-packages/pipsi.py", line 241, in install
    if repo.install(package, python):
  File "/home/phoenix/.local/venvs/pipsi/lib/python3.4/site-packages/pipsi.py", line 140, in install
    linked_scripts = self.link_scripts(scripts)
  File "/home/phoenix/.local/venvs/pipsi/lib/python3.4/site-packages/pipsi.py", line 86, in link_scripts
    for script in scripts:
  File "/home/phoenix/.local/venvs/pipsi/lib/python3.4/site-packages/pipsi.py", line 80, in find_scripts
    filename.startswith(prefix) and \
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

~/.local/venvs/tox is created, but ~/.local/bin/tox not.

**Comment by RonnyPfannschmidt** [comment]
should be fixed in PR#32 needs a test

**Comment by RonnyPfannschmidt** [comment]
is fixed in master

**Comment by untitaker** [comment]
Testsuite doesn't run under Python 3.
