### ISSUE TITLE
fails to install xonsh: "setup.py --name" includes logo

### ISSUE THREAD

**Issue by blueyed** [mitsuhiko/pipsi#53]
When trying to install xonsh with [pipsi](https://github.com/mitsuhiko/pipsi) it fails because xonsh's `setup.py` is fancy and [prints a logo](https://github.com/scopatz/xonsh/blob/c5ab05409dd5fe60e89a2f189815f58ae3ebc370/setup.py#L61)..

pipsi uses `setup.py --name` to get the name:

    % pipsi install -e ~v/xonsh 
    Traceback (most recent call last):
      File "/home/user/.local/bin/pipsi3", line 9, in <module>
        load_entry_point('pipsi==0.9.dev0', 'console_scripts', 'pipsi')()
      File "/home/user/.local/venvs3/pipsi/lib/python3.4/site-packages/click/core.py", line 664, in __call__
        return self.main(*args, **kwargs)
      File "/home/user/.local/venvs3/pipsi/lib/python3.4/site-packages/click/core.py", line 644, in main
        rv = self.invoke(ctx)
      File "/home/user/.local/venvs3/pipsi/lib/python3.4/site-packages/click/core.py", line 991, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/user/.local/venvs3/pipsi/lib/python3.4/site-packages/click/core.py", line 837, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/user/.local/venvs3/pipsi/lib/python3.4/site-packages/click/core.py", line 464, in invoke
        return callback(*args, **kwargs)
      File "/home/user/.local/venvs3/pipsi/lib/python3.4/site-packages/click/decorators.py", line 26, in new_func
        return ctx.invoke(f, ctx.obj, *args[1:], **kwargs)
      File "/home/user/.local/venvs3/pipsi/lib/python3.4/site-packages/click/core.py", line 464, in invoke
        return callback(*args, **kwargs)
      File "…/pipsi/pipsi.py", line 366, in install
        if repo.install(package, python, editable):
      File "…/pipsi/pipsi.py", line 215, in install
        venv_path = self.get_package_path(package)
      File "…/pipsi/pipsi.py", line 187, in get_package_path
        return join(self.home, normalize_package(package))
      File "…/pipsi/pipsi.py", line 61, in normalize_package
        requirement = Requirement.parse(value)
      File "/home/user/.local/venvs3/pipsi/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2986, in parse
        reqs = list(parse_requirements(s))
      File "/home/user/.local/venvs3/pipsi/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2917, in parse_requirements
        raise RequirementParseError("Missing distribution spec", line)
    pkg_resources.RequirementParseError: Missing distribution spec ╓██▄

Initially reported for xonsh at: https://github.com/scopatz/xonsh/issues/288 and I've been asked to also report it for pipsi.

What do you think?
Should xonsh just don't output the logo altogether?
Is there a good way for xonsh to only output the logo in "safe" circumstances?
Can pipsi do something about this?

**Comment by RonnyPfannschmidt** [comment]
this is a bug i also just recently noticed, pipsi currently expects to install pypi packages, with optional version specs

the solution is of course not to do requirement parsing in the case an actual path is involved
however this brings us to a very dire problem 

if a path is used, pipsi has no idea what package i did just install

this is a fundamental shortcoming i hope we can tackle after #52 is solved

**Comment by RonnyPfannschmidt** [comment]
on further investigation it seems i might be misstaken

**Comment by RonnyPfannschmidt** [comment]
xonsh printing the logo completely breaks expected tooling behaviour

**Comment by untitaker** [comment]
We had a similar issue in [khal](https://github.com/geier/khal) because its setup.py created (used to create) a version.py and printed debugging information.

**Comment by scopatz** [comment]
@untitaker, I agree. I don't think that this is xonsh-specific issue.  I could not find anything in the Python setup.py docs that disallows the setup script from taking other actions (such as printing) other than calling the `setup()` function. Forcing all packages into this mode is probably not a sustainable system, given how many packages there are.

Other tools like conda build and pip itself handle setup.py files that print extra information without error.  

I am happy to help implement another hook in xonsh to find the package name, if you let me know what to do. I want my tool to work with your tool. Maybe a pipsi config file would be beneficial?

**Comment by RonnyPfannschmidt** [comment]
pip forces setuptools onto all packages and extracts the first egg_info it finds,
such hack is a rather complex pain,
it tends to be way more sustainable to just report issues to packages that play the fancy card because they can,
because one of the reasons why packaging is such a mess is because packages to whatever they want if they can

**Comment by untitaker** [comment]
I don't think this is an issue that can be fixed in pipsi. Packages that break like this have to be fixed.

**Comment by RonnyPfannschmidt** [comment]
actually i fixed 1-2 weeks ago (xonsh)
