### ISSUE TITLE
Cannot install on Windows

### ISSUE THREAD

**Issue by uioporqwerty** [mitsuhiko/pipsi#58]
Executing the `curl -skS https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python` results in the following error:

 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2805  100  2805    0     0   3404      0 --:--:-- --:--:-- --:--:--  4112
Installing pipsi
Using base prefix 'c:\\python34'
New python executable in /home/nsachar/.local/venvs/pipsi\Scripts\python.exe
Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "<stdin>", line 118, in <module>
  File "<stdin>", line 94, in main
  File "<stdin>", line 74, in install_files
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by mythmon** [comment]
This seems to be a duplicate of #9.

**Comment by RonnyPfannschmidt** [comment]
That looks like a virtualenv issue
