### ISSUE TITLE
pips fails on `list` when nothing installed

### ISSUE THREAD

**Issue by zbeekman** [mitsuhiko/pipsi#66]
It would be great to have meaningful output when no packages have been installed yet, but the user runs `pipsi list`. Right now this is the result on my system:

```
$ pipsi list
Packages and scripts installed through pipsi:
Traceback (most recent call last):
  File "/usr/local/bin/pipsi", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipsi.py", line 416, in list_cmd
    for venv, scripts in repo.list_everything():
  File "/usr/local/lib/python2.7/site-packages/pipsi.py", line 307, in list_everything
    for venv in os.listdir(self.home):
OSError: [Errno 2] No such file or directory: '/Users/ibeekman/.local/venvs'
```

This might help in creating an acceptable `test do` block in a Homebrew formula. (See #60 )

**Comment by Siecje** [comment]
When I run it with nothing installed I see ```pipsi```.
```shell
$pipsi list
Packages and scripts installed through pipsi:
  Package "pipsi":
    pipsi
```

**Comment by bddenhartog** [comment]
@Siecje You've installed `pipsi` using `pipsi`. I can confirm that this is an issue after a fresh installation of `pipsi`:

```text
$ pip install --user pipsi
> ...
> Installing collected packages: Click, virtualenv, pipsi
> Successfully installed Click pipsi virtualenv

$ pipsi list
Packages and scripts installed through pipsi:
Traceback (most recent call last):
  File "/home/username/.local/bin/pipsi", line 11, in <module>
    sys.exit(cli())
  File "/home/username/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/username/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/username/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/username/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/username/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/username/.local/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/username/.local/lib/python2.7/site-packages/pipsi.py", line 416, in list_cmd
    for venv, scripts in repo.list_everything():
  File "/home/username/.local/lib/python2.7/site-packages/pipsi.py", line 307, in list_everything
    for venv in os.listdir(self.home):
OSError: [Errno 2] No such file or directory: '/home/username/.local/venvs'
```

It would appear that the error occurs because the `$HOME/.local/venvs` directory, which is where `pipsi` installs packages within virtual environments, does not exist. Simply creating this directory (with `mkdir ~/.local/venvs`) resolves this issue.

`pipsi` should be refactored to test for existence of the directory before attempting to list packages in it.

**Comment by bddenhartog** [comment]
@Siecje You've installed `pipsi` using `pipsi`. I can confirm that this is an issue after a fresh installation of `pipsi`:

```text
$ pip install --user pipsi
...
Installing collected packages: Click, virtualenv, pipsi
Successfully installed Click pipsi virtualenv

$ pipsi list
Packages and scripts installed through pipsi:
Traceback (most recent call last):
  File "/home/username/.local/bin/pipsi", line 11, in <module>
    sys.exit(cli())
  File "/home/username/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/username/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/username/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/username/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/username/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/username/.local/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/username/.local/lib/python2.7/site-packages/pipsi.py", line 416, in list_cmd
    for venv, scripts in repo.list_everything():
  File "/home/username/.local/lib/python2.7/site-packages/pipsi.py", line 307, in list_everything
    for venv in os.listdir(self.home):
OSError: [Errno 2] No such file or directory: '/home/username/.local/venvs'
```

It would appear that the error occurs because the `$HOME/.local/venvs` directory, which is where `pipsi` installs packages within virtual environments, does not exist. Simply creating this directory (with `mkdir ~/.local/venvs`) resolves this issue.

`pipsi` should be refactored to test for existence of the directory before attempting to list packages in it.
