### ISSUE TITLE
`pipsi` cannot determine its own version when invoked via `python -m pipsi`

### ISSUE THREAD

**Issue by wsanchez** [mitsuhiko/pipsi#86]
`pipsi` cannot determine its own version when invoked as `python -m pipsi`:

```
[~] wsanchez$ pipsi --version
pipsi, version 0.9, python /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
[~] wsanchez$ python -m pipsi --version
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Library/Python/2.7/site-packages/pipsi.py", line 424, in <module>
    cli()
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 695, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/Library/Python/2.7/site-packages/click/core.py", line 620, in make_context
    self.parse_args(ctx, args)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1012, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/Library/Python/2.7/site-packages/click/core.py", line 874, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1398, in handle_parse_result
    self.callback, ctx, self, value)
  File "/Library/Python/2.7/site-packages/click/core.py", line 77, in invoke_param_callback
    return callback(ctx, param, value)
  File "/Library/Python/2.7/site-packages/click/decorators.py", line 263, in callback
    raise RuntimeError('Could not determine version')
RuntimeError: Could not determine version
[~] wsanchez$ 
```

**Comment by RonnyPfannschmidt** [comment]
this is a bug in click at determining the origin module of a command
